# automatically format code using clang-format when a pull request is merged or manually triggered
name: format-code

on:
  pull_request:
    types: [closed]  # on merge pull request
  workflow_dispatch: # allows manual triggering

permissions:
  contents: write

jobs:
  auto-format:
    uses: abucky0/lemlib-common-files-test/.github/workflows/auto-format.yml@main
