name: Populate Depot json

on: 
  # runs when this repository's releases are modified
  release: 
  # allows for manual dispatching of the workflow
  workflow_dispatch: 

jobs:
  populate:
    uses: ABUCKY0/lemlib-common-files-test/.github/workflows/depot.yml@main
    with:
      target-repo: "ABUCKY0/LemLib"
      source-repo: "ABUCKY0/LemLib"
