name: Add Template to Pull Request 

on:
  workflow_run:
    workflows: ['PROS Build Template']
    types: [completed]

  workflow_dispatch: 

jobs:
  pr-comment:
    uses: LemLib/common-files/.github/workflows/pr-comment.yml@main
