name: PROS Build Example

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

  workflow_dispatch: 

jobs:
  build:
    uses: abucky0/lemlib-common-files-test/.github/workflows/pros-build.yml@main
