name: test-clang-format

on:
  push:
    branches:
      - '*'
  pull_request:


jobs:
  clang-format:
    uses: LemLib/common-files/.github/workflows/test-clang-format.yml@main
    with:
      source: './src/lemlib ./include/lemlib'
